apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-mysql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculty-mysql-service
  template:
    metadata:
      labels:
        app: faculty-mysql-service
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.36
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Asmae.2020"
            - name: MYSQL_DATABASE
              value: "faculty_db"
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 40
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: faculty-mysql-service
spec:
  type: ClusterIP
  selector:
    app: faculty-mysql-service
  ports:
    - port: 3306
      targetPort: 3306
