apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS faculty_student_db;
    CREATE DATABASE IF NOT EXISTS faculty_filiere_db;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-mysql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculty-mysql-service
  template:
    metadata:
      labels:
        app: faculty-mysql-service
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.36
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Asmae.2020"
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 40
            periodSeconds: 20
      volumes:
        - name: initdb
          configMap:
            name: mysql-initdb
---
apiVersion: v1
kind: Service
metadata:
  name: faculty-mysql-service
spec:
  type: ClusterIP
  selector:
    app: faculty-mysql-service
  ports:
    - port: 3306
      targetPort: 3306
