apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-mysql-service
spec:
  selector:
    matchLabels:
      app: faculty-mysql-service
  replicas: 1
  template:
    metadata:
      labels:
        app: faculty-mysql-service
    spec:
      containers:
        - name: faculty-mysql-service
          image: mysql:latest
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'yes'
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: faculty-mysql-service
spec:
  selector:
    app: faculty-mysql-service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer